nav:
- Home: index.md
- Requirements: requirements.md
- Installation: installation.md
- Usage: usage.md
- About:
  - License: license.md
  - Release Notes: https://github.com/project-sthali/sthali-core/releases
  - Issue Tracker: https://github.com/project-sthali/sthali-core/issues
- API Reference:
  - App: api/class_App.md
  - AppSpecification: api/class_AppSpecification.md
  - Config: api/class_Config.md
  - base: api/module_base.md
  - enum_clients: api/module_enum_clients.md
  - run_server: api/module_run_server.md
repo_name: sthali-core
repo_url: https://github.com/project-sthali/sthali-core/
site_author: Jhunu Fernandes
site_description: A core package for Sthali development
site_name: sthali-core
site_url: https://project-sthali.github.io/sthali-core/
theme: readthedocs
